<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>SimEngine.Client</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Akka.Remote" />
    <PackageReference Include="Akka.Cluster" />
    <PackageReference Include="Akka.Cluster.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimEngine.Contracts\SimEngine.Contracts.csproj" />
  </ItemGroup>

</Project>
