<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SimEngine.Game.Ui.Console</RootNamespace>
    <AssemblyName>SimEngine.Game.Ui.Console</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimEngine\SimEngine.csproj" />
    <ProjectReference Include="..\SimEngine.Game\SimEngine.Game.csproj" />
    <ProjectReference Include="..\SimEngine.Contracts\SimEngine.Contracts.csproj" />
    <ProjectReference Include="..\SimEngine.Server\SimEngine.Server.csproj" />
    <ProjectReference Include="..\SimEngine.Client\SimEngine.Client.csproj" />
    <ProjectReference Include="..\SimEngine.Rendering\SimEngine.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Akka.Remote" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SimEngine.Tests" />
  </ItemGroup>

</Project>
