<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>SimEngine.Game.Ui.Stride</RootNamespace>
        <AssemblyName>SimEngine.Game.Ui.Stride</AssemblyName>
        <NoWarn>$(NoWarn);NU1901;NU1903</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Stride.CommunityToolkit.Windows" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\SimEngine.Game\SimEngine.Game.csproj" />
    </ItemGroup>

</Project>
