<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SimEngine.ConsoleHost</RootNamespace>
    <AssemblyName>SimEngine.ConsoleHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimEngine\SimEngine.csproj" />
    <ProjectReference Include="..\SimEngine.Game\SimEngine.Game.csproj" />
    <ProjectReference Include="..\SimEngine.Contracts\SimEngine.Contracts.csproj" />
    <ProjectReference Include="..\SimEngine.Server\SimEngine.Server.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\tests\SimEngine.Tests\TestAssets\grid4.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\grid4.geojson</Link>
    </Content>
    <Content Include="..\..\tests\SimEngine.Tests\TestAssets\germany_admin1.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\germany_admin1.geojson</Link>
    </Content>
  </ItemGroup>

</Project>
