<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>SimEngine.ConsoleHost</RootNamespace>
    <AssemblyName>SimEngine.ConsoleHost</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimEngine\SimEngine.csproj" />
    <ProjectReference Include="..\SimEngine.Game\SimEngine.Game.csproj" />
    <ProjectReference Include="..\SimEngine.Contracts\SimEngine.Contracts.csproj" />
    <ProjectReference Include="..\SimEngine.Server\SimEngine.Server.csproj" />
    <ProjectReference Include="..\SimEngine.Rendering\SimEngine.Rendering.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Microsoft.Orleans.Server" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SimEngine.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\data\custom-test\grid4.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\grid4.geojson</Link>
    </Content>
    <Content Include="..\..\data\germany-test\germany_admin1.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\germany_admin1.geojson</Link>
    </Content>
    <Content Include="..\..\data\europe-west\europe_west_admin1.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\europe_west_admin1.geojson</Link>
    </Content>
    <Content Include="..\..\data\full-world\states\world_admin1.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\world_admin1.geojson</Link>
    </Content>
    <Content Include="..\..\data\custom-test\grid4.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\grid4.countries.json</Link>
    </Content>
    <Content Include="..\..\data\germany-test\germany_admin1.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\germany_admin1.countries.json</Link>
    </Content>
    <Content Include="..\..\data\europe-west\europe_west_admin1.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\europe_west_admin1.countries.json</Link>
    </Content>
    <Content Include="..\..\data\full-world\countries\world_admin1.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\world_admin1.countries.json</Link>
    </Content>
    <Content Include="..\..\data\full-world\marineregions\world_eez.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\marineregions\world_eez.geojson</Link>
    </Content>
  </ItemGroup>

</Project>
