<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SimEngine.Server</RootNamespace>
    <AssemblyName>SimEngine.Server</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Akka" />
    <PackageReference Include="Akka.Hosting" />
    <PackageReference Include="Akka.Remote" />
    <PackageReference Include="Akka.Cluster" />
    <PackageReference Include="Akka.Cluster.Sharding" />
    <PackageReference Include="Akka.Cluster.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimEngine.Contracts\SimEngine.Contracts.csproj" />
    <ProjectReference Include="..\SimEngine\SimEngine.csproj" />
    <ProjectReference Include="..\SimEngine.Game\SimEngine.Game.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Grains\" />
  </ItemGroup>
</Project>
