<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA2007</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Orleans.TestingHost" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SimEngine.Contracts\SimEngine.Contracts.csproj" />
    <ProjectReference Include="..\..\src\SimEngine.Server\SimEngine.Server.csproj" />
    <ProjectReference Include="..\..\src\SimEngine.Client\SimEngine.Client.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\..\data\custom-test\grid4.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\grid4.geojson</Link>
    </Content>
    <Content Include="..\..\data\germany-test\germany_admin1.geojson">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\germany_admin1.geojson</Link>
    </Content>
    <Content Include="..\..\data\custom-test\grid4.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\grid4.countries.json</Link>
    </Content>
    <Content Include="..\..\data\germany-test\germany_admin1.countries.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Worlds\germany_admin1.countries.json</Link>
    </Content>
  </ItemGroup>
</Project>
