<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SimEngine</RootNamespace>
    <AssemblyName>SimEngine</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="SimEngine.Tests" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NetTopologySuite" />
    <PackageReference Include="NetTopologySuite.IO.GeoJSON" />
  </ItemGroup>
</Project>
